adding tool version and absolute paths in pheval run parameters
monarch-initiative/pheval pull request #151
Opened 2023-06-08 09:00 UTC by souzadevinicius

fixes #150

2023-06-08 09:12 UTC, matentzn commented on resources/Makefile.j2
> +	 --phenopacket-dir=$(shell pwd)/$(TEST_DATA)/phenopackets/lirical
The `phenopacket-dir` should be tied to the dependencies of this make goal..

2023-06-08 09:37 UTC, souzadevinicius commented on resources/Makefile.j2
> +	 --input-dir $(shell pwd)/{{ directories.config }}/{{ run.tool }}-{{ run.version }}-{{ run.configuration }} \
Yep, it's a good solution ;)

2023-06-12 11:01 UTC, matentzn requested changes
Some minor changes! 

AMAZING work, super complex issue, and well done.

2023-06-12 17:09 UTC, yaseminbridges commented on corpora/lirical/default/phenopackets/Abdul_Wahab-2016-GCDH-Patient_5.json
Is it possible to revert the phenopackets back to the original state? When the `files` section is empty

2023-06-12 17:12 UTC, yaseminbridges commented on resources/pheval-config.yaml
> +      - id: no_phenotype
What does the `custom_variants` mean?

2023-06-12 18:46 UTC, yaseminbridges commented on corpora/lirical/default/phenopackets/Abdul_Wahab-2016-GCDH-Patient_5.json
All of the LIRICAL phenopackets now have an added `files` section, e.g.,

```yaml
 "files": [
     {
       "uri": "file:///home/vinicius/workspace/pheval/corpora/lirical/scrambled-0.5/vcf/Abdul_Wahab-2016-GCDH-Patient_5.vcf.gz",
       "fileAttributes": {
         "fileFormat": "vcf",
         "genomeAssembly": "GRCh37"
       }
     }
   ],
```

I had removed this section before in an earlier PR. It looks to be only the LIRICAL phenopackets that have this section added and moved- the rest have stayed the same and just changed location.

2023-06-12 18:46 UTC, yaseminbridges commented on resources/pheval-config.yaml
> +      - id: no_phenotype
Ah, got it!

2023-06-12 19:59 UTC, souzadevinicius commented on corpora/lirical/default/phenopackets/Abdul_Wahab-2016-GCDH-Patient_5.json
Is there a step that overwrites the URI attribute?
Yes, I can revert them, but ideally, pheval shouldn't change these values, right?

2023-06-12 20:45 UTC, yaseminbridges commented on corpora/lirical/default/phenopackets/Abdul_Wahab-2016-GCDH-Patient_5.json
There isn't a step that overwrites the URI attribute a new `File` object will be created. I think we want PhEval to add the reference of the VCF as it's related to the sample, plus,  I use the genome assembly information and VCF file name from here.

2023-06-13 09:38 UTC, matentzn commented on corpora/lirical/default/phenopackets/Abdul_Wahab-2016-GCDH-Patient_5.json
@souzadevinicius do you undestand what needs to be done here? Not following the convo. Is this a matter of updating the PR from `main` branch?

2023-06-13 12:12 UTC, matentzn approved these changes

2023-06-14 03:59 UTC, merged